INSERT INTO filme (nome, ano, descricao) VALUES
('O Poderoso Chefão', 1972, 'A saga da família mafiosa Corleone, liderada por Don Vito Corleone.'),
('O Senhor dos Anéis: A Sociedade do Anel', 2001, 'Um hobbit embarca em uma jornada para destruir um anel poderoso.'),
('Pulp Fiction', 1994, 'Histórias entrelaçadas de crime e redenção em Los Angeles.'),
('A Origem', 2010, 'Um ladrão que invade sonhos é contratado para plantar uma ideia na mente de um CEO.'),
('Matrix', 1999, 'Um hacker descobre a verdade sobre sua realidade e seu papel na guerra contra seus controladores.'),
('Forrest Gump', 1994, 'A vida extraordinária de um homem simples com um coração puro.'),
('Clube da Luta', 1999, 'Um trabalhador de escritório insatisfeito forma um clube de luta clandestino.'),
('Interestelar', 2014, 'Exploradores espaciais viajam através de um buraco de minhoca em busca de um novo lar para a humanidade.'),
('Gladiador', 2000, 'Um general romano busca vingança contra o imperador corrupto que matou sua família.'),
('O Cavaleiro das Trevas', 2008, 'Batman enfrenta o Coringa, um criminoso psicopata que quer destruir Gotham City.'),
('Titanic', 1997, 'Um romance trágico a bordo do infame navio Titanic.'),
('Os Infiltrados', 2006, 'Um policial disfarçado e um informante da máfia tentam descobrir a identidade um do outro.'),
('A Lista de Schindler', 1993, 'A história real de um empresário que salvou milhares de judeus durante o Holocausto.'),
('Vingadores: Ultimato', 2019, 'Os Vingadores se unem para derrotar Thanos e restaurar o universo.'),
('O Silêncio dos Inocentes', 1991, 'Uma jovem agente do FBI busca a ajuda de um assassino canibal para capturar outro serial killer.'),
('Coringa', 2019, 'A origem sombria do icônico vilão do Batman, o Coringa.'),
('O Resgate do Soldado Ryan', 1998, 'Durante a Segunda Guerra Mundial, um grupo de soldados é enviado para resgatar um paraquedista.'),
('A Vida é Bela', 1997, 'Um pai usa humor para proteger seu filho dos horrores de um campo de concentração nazista.'),
('O Grande Truque', 2006, 'Dois mágicos rivais competem para criar o melhor truque de todos os tempos.'),
('Django Livre', 2012, 'Um escravo liberto se torna um caçador de recompensas e busca resgatar sua esposa.'),
('O Iluminado', 1980, 'Um escritor se torna violento enquanto cuida de um hotel isolado durante o inverno.');