INSERT INTO filme (nome, ano, descricao, imagem) VALUES
('O Poderoso Chefão', 1972, 'A saga da família mafiosa Corleone, liderada por Don Vito Corleone.', 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg'),
('O Senhor dos Anéis: A Sociedade do Anel', 2001, 'Um hobbit embarca em uma jornada para destruir um anel poderoso.', 'https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg'),
('Pulp Fiction', 1994, 'Histórias entrelaçadas de crime e redenção em Los Angeles.', 'https://m.media-amazon.com/images/I/71c05lTE03L._AC_SY679_.jpg'),
('A Origem', 2010, 'Um ladrão que invade sonhos é contratado para plantar uma ideia na mente de um CEO.', 'https://m.media-amazon.com/images/I/81p%2Bxe8cbnL._AC_SY679_.jpg'),
('Matrix', 1999, 'Um hacker descobre a verdade sobre sua realidade e seu papel na guerra contra seus controladores.', 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg'),
('Forrest Gump', 1994, 'A vida extraordinária de um homem simples com um coração puro.', 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg'),
('Clube da Luta', 1999, 'Um trabalhador de escritório insatisfeito forma um clube de luta clandestino.', 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg'),
('Interestelar', 2014, 'Exploradores espaciais viajam através de um buraco de minhoca em busca de um novo lar para a humanidade.', 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg'),
('O Rei Leão', 1994, 'Um jovem príncipe leão foge de seu reino apenas para aprender o verdadeiro significado de responsabilidade e coragem.', 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg'),
('De Volta para o Futuro', 1985, 'Um adolescente é acidentalmente enviado 30 anos para o passado em um DeLorean viajante do tempo.', 'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg'),
('Jurassic Park', 1993, 'Um parque temático sofre uma grande falha de energia que permite que seus dinossauros clonados escapem.', 'https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg'),
('O Grande Lebowski', 1998, 'Jeff "The Dude" Lebowski, um preguiçoso de Los Angeles, é confundido com um milionário do mesmo nome.', 'https://upload.wikimedia.org/wikipedia/en/3/35/Biglebowskiposter.jpg'),
('A Lista de Schindler', 1993, 'A história real de um empresário que salvou milhares de judeus durante o Holocausto.', 'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg'),
('Vingadores: Ultimato', 2019, 'Os Vingadores se unem para derrotar Thanos e restaurar o universo.', 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg'),
('O Silêncio dos Inocentes', 1991, 'Uma jovem agente do FBI busca a ajuda de um assassino canibal para capturar outro serial killer.', 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg'),
('Coringa', 2019, 'A origem sombria do icônico vilão do Batman, o Coringa.', 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg'),
('O Resgate do Soldado Ryan', 1998, 'Durante a Segunda Guerra Mundial, um grupo de soldados é enviado para resgatar um paraquedista.', 'https://upload.wikimedia.org/wikipedia/en/a/ac/Saving_Private_Ryan_poster.jpg'),
('O Grande Truque', 2006, 'Dois mágicos rivais competem para criar o melhor truque de todos os tempos.', 'https://upload.wikimedia.org/wikipedia/en/d/d2/Prestige_poster.jpg'),
('Django Livre', 2012, 'Um escravo liberto se torna um caçador de recompensas e busca resgatar sua esposa.', 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg'),
('A Origem dos Guardiões', 2012, 'Os guardiões imortais se unem para proteger as crianças do mundo de um espírito maligno.', 'https://upload.wikimedia.org/wikipedia/en/9/92/Rise_of_the_Guardians_poster.jpg');